# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_auto_20170202_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 2, 2, 8, 20, 22, 935427))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
