# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170202_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 8, 20, 22, 928217)),
        ),
    ]
