# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import people.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile', sorl.thumbnail.fields.ImageField(upload_to=people.models.image_path)),
            ],
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='category',
            field=models.ManyToManyField(to='people.StaffCategory'),
        ),
    ]
