# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import people.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=50)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from='name', unique=True)),
                ('profile', sorl.thumbnail.fields.ImageField(upload_to=people.models.image_path)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.ManyToManyField(blank=True, to='people.Category')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_category', to='people.Staff'),
        ),
    ]
