# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffCategory',
            new_name='Category',
        ),
    ]
