# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170201_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
