# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 12, 10, 12, 221619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 12, 10, 12, 222291, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 12, 10, 12, 222828, tzinfo=utc)),
        ),
    ]
