# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20170201_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='year',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='year',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='year',
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 1, 17, 51, 32, 227998)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 1, 17, 51, 32, 228564)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 1, 17, 51, 32, 229157)),
        ),
    ]
