# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20170203_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from='title', unique=True),
        ),
    ]
