# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_auto_20170201_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 1, 18, 8, 45, 346196)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 1, 18, 8, 45, 346752)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 1, 18, 8, 45, 347267)),
        ),
    ]
