# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_auto_20170202_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 12, 14, 2, 314685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 12, 14, 2, 315406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 12, 14, 2, 315960, tzinfo=utc)),
        ),
    ]
